defmodule Muro.EmitCTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  test "mix muro.emit --backend elixir matches emit_file" do
    path = "examples/half_ok.muro"
    assert {:ok, src} = Muro.emit_file(path, HalfOk)
    assert src =~ "def plus"
    assert src =~ "def half"
    refute src =~ "defp pred"
    refute src =~ "def half_ok"

    out = capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "elixir"]) end)
    assert String.trim_trailing(out) == String.trim_trailing(src)

    out = capture_io(fn -> Mix.Tasks.Muro.Emit.run([path]) end)
    assert String.trim_trailing(out) == String.trim_trailing(src)
  end

  test "mix muro.emit --backend c compiles half_ok" do
    dir = tmp_dir()
    path = Path.join(dir, "half_ok.muro")
    File.cp!("examples/half_ok.muro", path)

    out = capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)

    h = Path.join(dir, "half_ok.h")
    c = Path.join(dir, "half_ok.c")
    assert out =~ h
    assert out =~ c

    header = File.read!(h)
    source = File.read!(c)

    assert header =~ "/* generated by muro — do not edit */"
    assert header =~ "struct muro_nat { uint8_t tag; muro_nat *suc; }; /* 0 = zero, 1 = suc */"
    assert header =~ "muro_nat *half(muro_nat *n);"
    assert header =~ "muro_nat *plus(muro_nat *n, muro_nat *m);"
    assert header =~ "#ifndef MURO_ALLOC"
    assert header =~ "#define MURO_ALLOC(n) malloc(n)"
    refute header =~ "IsEven"
    refute header =~ "half_ok("

    assert source =~ "muro_zero"
    assert source =~ "muro_suc"
    refute source =~ "static muro_nat *half"
    assert source =~ "half("
    assert source =~ "MURO_ALLOC(sizeof *p)"
    refute source =~ "malloc("

    cc!(dir, "half_ok.c", "half_ok.o")
  end

  test "a run Stream compiles as a seed and a step, and Elixir still uses Stream.unfold" do
    dir = tmp_dir()

    for name <- ["zeros", "nats"] do
      path = Path.join(dir, "#{name}.muro")
      File.cp!("examples/#{name}.muro", path)
      capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
      cc!(dir, "#{name}.c", "#{name}.o")
    end

    header = File.read!(Path.join(dir, "nats.h"))
    source = File.read!(Path.join(dir, "nats.c"))
    assert header =~ "typedef struct muro_stream muro_stream;"
    assert header =~ "muro_stream *natsFrom(muro_nat *n);"
    assert source =~ "struct muro_stream {"
    assert source =~ "void *seed;"
    assert source =~ "muro_pair *(*step)(void *env, void *seed);"
    assert source =~ "static muro_pair *muro_step_0(void *muro_envp, void *muro_seedp)"
    assert source =~ "muro_stream_new(n, 0, muro_step_0)"
    assert source =~ "p->seed = seed;"

    assert {:ok, src} = Muro.emit_file("examples/zeros.muro", Zeros)
    assert src =~ "Stream.unfold"

    out =
      capture_io(fn ->
        Mix.Tasks.Muro.Emit.run(["examples/zeros.muro", "--backend", "elixir"])
      end)

    assert out =~ "Stream.unfold"
  end

  test "uncons builds a new stream and a capturing step keeps the outer value" do
    dir = tmp_dir()

    head = Path.join(dir, "head_stream.muro")

    File.write!(head, """
    ν Stream (A : Type) : Type where
      uncons : Stream A → A × Stream A

    def zeros : run Stream Nat :=
      unfold 0 (λ (_ : Nat) → (0, 0))

    def hd : run Π (s : Stream Nat) → Nat :=
      λ (s : Stream Nat) → head s
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([head, "--backend", "c"]) end)
    source = File.read!(Path.join(dir, "head_stream.c"))
    assert source =~ "->step("
    assert source =~ "muro_stream_new("
    cc!(dir, "head_stream.c", "head_stream.o")

    prefix = Path.join(dir, "prefix.muro")

    File.write!(prefix, """
    ν Stream (A : Type) : Type where
      uncons : Stream A → A × Stream A

    def prefix : run Π (n : Nat) → Stream Nat :=
      λ (n : Nat) →
        unfold 0 (λ (_ : Nat) → (n, 0))
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([prefix, "--backend", "c"]) end)
    pref = File.read!(Path.join(dir, "prefix.c"))
    assert pref =~ "muro_env_0"
    assert pref =~ "muro_ep0->n = n;"
    cc!(dir, "prefix.c", "prefix.o")
  end

  test "a lambda applied on the spot is a local" do
    dir = tmp_dir()
    path = Path.join(dir, "apply_lam.muro")

    File.write!(path, """
    def id : run Π (n : Nat) → Nat :=
      λ (n : Nat) → (λ (m : Nat) → suc m) n

    def snd : run Π (n : Nat) → Π (m : Nat) → Nat :=
      λ (n : Nat) → λ (m : Nat) → ((λ (x : Nat) → λ (y : Nat) → y) n) m

    def keep : run Π (n : Nat) → Nat :=
      λ (n : Nat) → (λ (- k : Nat) → n) 0
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
    source = File.read!(Path.join(dir, "apply_lam.c"))
    assert source =~ "muro_nat *muro_s0 = n;"
    assert source =~ "muro_suc(muro_s0)"
    assert source =~ "muro_nat *muro_s1 = m;"
    refute source =~ "muro_zero()"
    cc!(dir, "apply_lam.c", "apply_lam.o")
  end

  test "a lambda that is passed as a value is refused" do
    dir = tmp_dir()
    path = Path.join(dir, "lam.muro")

    File.write!(path, """
    def bad : run Π (f : Π (x : Nat) → Nat) → Nat :=
      λ (f : Π (x : Nat) → Nat) → f 0
    """)

    assert_raise Mix.Error, ~r/c:lambda/, fn ->
      Mix.Tasks.Muro.Emit.run([path, "--backend", "c"])
    end
  end

  test "evidence Always is omitted from the C file" do
    dir = tmp_dir()
    path = Path.join(dir, "always.muro")
    File.cp!("examples/always.muro", path)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
    source = File.read!(Path.join(dir, "always.c"))
    assert source =~ "muro_stream_new"
    refute source =~ "zeros-always-zero"
    cc!(dir, "always.c", "always.o")
  end

  test "I64 and Tensor are refused by C and still emitted as Elixir" do
    assert_raise Mix.Error, ~r/c:machine/, fn ->
      Mix.Tasks.Muro.Emit.run(["examples/nx_add.muro", "--backend", "c"])
    end

    assert {:ok, src} = Muro.emit_file("examples/nx_add.muro", NxAdd)
    assert src =~ "Nx.add"
  end

  test "run internal is static and list data compiles" do
    dir = tmp_dir()

    internal = Path.join(dir, "internal_ok.muro")
    File.cp!("examples/internal_ok.muro", internal)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([internal, "--backend", "c"]) end)

    header = File.read!(Path.join(dir, "internal_ok.h"))
    source = File.read!(Path.join(dir, "internal_ok.c"))
    assert header =~ "muro_nat *inc(muro_nat *n);"
    refute header =~ "step"
    assert source =~ "static muro_nat *step(muro_nat *n)"
    cc!(dir, "internal_ok.c", "internal_ok.o")

    File.cp!("examples/list.muro", Path.join(dir, "list.muro"))
    sort = Path.join(dir, "sort.muro")
    File.cp!("examples/sort.muro", sort)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([sort, "--backend", "c"]) end)
    sort_h = File.read!(Path.join(dir, "sort.h"))
    sort_c = File.read!(Path.join(dir, "sort.c"))
    assert sort_h =~ "typedef enum {"
    assert sort_h =~ "MURO_ASC"
    assert sort_h =~ "MURO_DESC"
    refute sort_c =~ "\"asc\""
    refute sort_c =~ "\"desc\""
    assert sort_c =~ "switch"
    cc!(dir, "sort.c", "sort.o")

    list = Path.join(dir, "list.muro")
    File.cp!("examples/list.muro", list)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([list, "--backend", "c"]) end)
    list_h = File.read!(Path.join(dir, "list.h"))
    assert list_h =~ "muro_list"
    assert list_h =~ "muro_nat *length(muro_list *xs);"
    cc!(dir, "list.c", "list.o")
  end

  test "atom spellings that sanitize together get distinct enumerators" do
    dir = tmp_dir()
    path = Path.join(dir, "atoms.muro")

    File.write!(path, """
    def pick : run Π (a : Atom) → Nat :=
      λ (a : Atom) →
        match a motive (λ _ → Nat)
          | :A => 0
          | :a => suc 0
          | :a-b => 0
          | :a_b => suc 0
          | :a' => 0
          | :a_ => suc 0
          | :asc => 0
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
    header = File.read!(Path.join(dir, "atoms.h"))
    source = File.read!(Path.join(dir, "atoms.c"))
    assert header =~ "MURO_A,"
    assert header =~ "MURO_A_2"
    assert header =~ "MURO_A_B,"
    assert header =~ "MURO_A_B_2"
    assert header =~ "MURO_A_,"
    assert header =~ "MURO_A__2"
    assert header =~ "MURO_ASC"
    refute header =~ "MURO_ASC_2"
    assert source =~ "case MURO_A:"
    assert source =~ "case MURO_A_2:"
    assert source =~ "case MURO_ASC:"
    cc!(dir, "atoms.c", "atoms.o")
  end

  test "C keywords and library names are prefixed" do
    dir = tmp_dir()
    path = Path.join(dir, "reserved.muro")

    File.write!(path, """
    data Bool : Type where
      true : Bool
      false : Bool

    def read : run Π (close : Bool) → Nat :=
      λ (close : Bool) →
        match close motive (λ _ → Nat)
          | true => 0
          | false => suc 0

    def write : run Nat := 0
    def delete : run Nat := 0
    def error : run Nat := 0
    def uint8_t : run Nat := 0
    def keep : run Nat := write
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
    header = File.read!(Path.join(dir, "reserved.h"))
    source = File.read!(Path.join(dir, "reserved.c"))
    assert header =~ "muro_nat *muro_read(muro_bool *muro_close)"
    assert header =~ "muro_nat *muro_write(void)"
    assert header =~ "muro_nat *muro_delete(void)"
    assert header =~ "muro_nat *muro_error(void)"
    assert header =~ "muro_nat *muro_uint8_t(void)"
    assert header =~ "muro_nat *keep(void)"
    refute header =~ ~r/(?<![\w])read\(/
    assert source =~ "static muro_bool *muro_true(void)"
    assert source =~ "static muro_bool *muro_false(void)"
    refute source =~ ~r/(?<![\w])true\(/
    cc!(dir, "reserved.c", "reserved.o", [c23_flag()])

    harness = Path.join(dir, "harness.c")

    File.write!(harness, """
    #include <unistd.h>
    #include <stdbool.h>
    #include "reserved.h"
    """)

    cc!(dir, "harness.c", "harness.o", [c23_flag()])
  end

  test "a constructor with no fields is one static object" do
    dir = tmp_dir()
    path = Path.join(dir, "nullary.muro")

    File.write!(path, """
    data Bool : Type where
      true : Bool
      false : Bool

    data Wrap : Type where
      bare : Wrap
      box : Nat → Wrap

    data Tok : Nat → Type where
      zed : Π (- n : Nat) → Tok n
      one : Π (- n : Nat) → Nat → Tok n

    def pick : run Π (b : Bool) → Wrap :=
      λ (b : Bool) →
        match b motive (λ _ → Wrap)
          | true => bare
          | false => box 0

    def tok0 : run Tok 0 :=
      zed 0
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
    source = File.read!(Path.join(dir, "nullary.c"))
    assert source =~ "static muro_bool muro_bool_true_obj = {0};"
    assert source =~ "static muro_bool *muro_true(void) { return &muro_bool_true_obj; }"
    assert source =~ "static muro_bool muro_bool_false_obj = {1};"
    assert source =~ "static muro_bool *muro_false(void) { return &muro_bool_false_obj; }"
    assert source =~ "static muro_wrap muro_wrap_bare_obj = {0};"
    assert source =~ "static muro_wrap *bare(void) { return &muro_wrap_bare_obj; }"
    assert source =~ "static muro_tok muro_tok_zed_obj = {0};"
    assert source =~ "static muro_tok *zed(void) { return &muro_tok_zed_obj; }"
    assert source =~ "static muro_wrap *box(muro_nat *f0) {"
    assert source =~ "muro_wrap *p = MURO_ALLOC(sizeof *p);"
    assert source =~ "static muro_tok *one(muro_nat *f0) {"
    refute source =~ "muro_bool *p = MURO_ALLOC"
    refute source =~ "muro_muro_bool"
    cc!(dir, "nullary.c", "nullary.o")

    list = Path.join(dir, "list.muro")
    File.cp!("examples/list.muro", list)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([list, "--backend", "c"]) end)
    list_c = File.read!(Path.join(dir, "list.c"))
    assert list_c =~ "static muro_list muro_list_nil_obj = {0};"
    assert list_c =~ "static muro_list *nil(void) { return &muro_list_nil_obj; }"
    assert list_c =~ "static muro_list *cons(void *f0, muro_list *f1) {"
    assert list_c =~ "muro_list *p = MURO_ALLOC(sizeof *p);"
    cc!(dir, "list.c", "list.o")
  end

  test "MURO_ALLOC can be one block that resets after a call" do
    dir = tmp_dir()
    path = Path.join(dir, "call.muro")

    File.write!(path, """
    data Bool : Type where
      true : Bool

    def two : run Nat := suc (suc 0)
    def flag : run Bool := true
    """)

    capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)
    header = File.read!(Path.join(dir, "call.h"))
    source = File.read!(Path.join(dir, "call.c"))
    assert header =~ "#define MURO_ALLOC(n) malloc(n)"
    assert source =~ "MURO_ALLOC(sizeof *p)"
    assert source =~ "static muro_bool muro_bool_true_obj = {0};"
    refute source =~ "malloc("
    cc!(dir, "call.c", "call.o")

    File.write!(Path.join(dir, "arena.h"), """
    #include <stddef.h>
    #define MURO_ALLOC(n) muro_arena_alloc(n)
    void *muro_arena_alloc(size_t n);
    extern size_t muro_arena_at;
    """)

    File.write!(Path.join(dir, "arena.c"), """
    #include "arena.h"

    static unsigned char block[1 << 16];
    size_t muro_arena_at;

    void *muro_arena_alloc(size_t n) {
      size_t at = (muro_arena_at + 7u) & ~(size_t)7u;
      if (n > sizeof block || at > sizeof block - n) return 0;
      muro_arena_at = at + n;
      return block + at;
    }
    """)

    File.write!(Path.join(dir, "main.c"), """
    #include "arena.h"
    #include "call.h"

    static int nats(muro_nat *n) {
      int k = 0;
      while (n->tag == 1) {
        n = n->suc;
        k++;
      }
      return k;
    }

    int main(void) {
      muro_nat *a = two();
      int n1 = nats(a);
      size_t used = muro_arena_at;
      muro_bool *f = flag();
      size_t after_flag = muro_arena_at;
      muro_arena_at = 0;
      muro_nat *b = two();
      int n2 = nats(b);
      if (n1 != 2 || n2 != 2) return 1;
      if (used == 0 || muro_arena_at != used) return 2;
      if (after_flag != used) return 3;
      if (f != flag()) return 4;
      return 0;
    }
    """)

    cc!(dir, "call.c", "call_arena.o", ~w(-include arena.h))
    cc!(dir, "arena.c", "arena.o")
    cc!(dir, "main.c", "main.o")

    {link, status} =
      System.cmd("cc", ~w(call_arena.o arena.o main.o -o call_bin),
        cd: dir,
        stderr_to_stdout: true
      )

    assert status == 0, link

    {out, status} = System.cmd(Path.join(dir, "call_bin"), [], stderr_to_stdout: true)
    assert status == 0, out
  end

  # GCC 14 and Clang spell this `-std=c23`. GCC 13, which Ubuntu 24.04
  # ships, only accepts the earlier name `-std=c2x`. Both reject `true`.
  defp c23_flag do
    if cc_accepts?("-std=c23"), do: "-std=c23", else: "-std=c2x"
  end

  defp cc_accepts?(flag) do
    src = Path.join(System.tmp_dir!(), "muro_cc_#{System.unique_integer([:positive])}.c")
    obj = Path.rootname(src) <> ".o"
    File.write!(src, "int x;\n")

    {_out, status} =
      System.cmd("cc", [flag, "-c", src, "-o", obj], stderr_to_stdout: true)

    File.rm(src)
    File.rm(obj)
    status == 0
  end

  defp tmp_dir do
    dir = Path.join(System.tmp_dir!(), "muro_c_#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp cc!(dir, src, obj, extra \\ []) do
    {out, status} =
      System.cmd("cc", extra ++ ["-c", src, "-o", obj], cd: dir, stderr_to_stdout: true)

    assert status == 0, out
  end
end
