defmodule Muro.Emit do
  @moduledoc """
  Emit run definitions to Elixir. Specs and evidence erase.
  A spec never becomes evidence. Evidence never becomes a run.

  A checked run Stream is emitted as `Stream.unfold/2`. The pair in an
  unfold body is `{head, next_seed}`. `uncons` is two replayable views
  (`Enum.take/2` + `Stream.drop/2`); affinity was already checked.
  """

  alias Muro.Ast

  @doc """
  Run definitions in book order. Data, spec, and evidence are omitted.
  `run internal` stays in the list; its `export` flag is false.
  """
  def run_defs(book) when is_list(book) do
    Enum.filter(book, &(Map.get(&1, :kind, :def) != :data and &1.mode == :run))
  end

  def emit_module(module, book) when is_atom(module) do
    runs = run_defs(book)
    funs = runs |> Enum.map(&emit_def(&1, book)) |> Enum.join("\n\n")

    except =
      if Enum.any?(runs, &(&1.name == "length")) do
        "  import Kernel, except: [length: 1]\n"
      else
        ""
      end

    nat_helper =
      if Enum.any?(runs, &term_has_toi64?(&1.body)) do
        """
          defp muro_nat_to_int(0), do: 0
          defp muro_nat_to_int({:suc, n}), do: 1 + muro_nat_to_int(n)
        """
      else
        ""
      end

    """
    defmodule #{inspect(module)} do
      # Generated by Muro. Evidence never becomes a run.
    #{except}
    #{indent(funs, 2)}
    #{nat_helper}
    end
    """
  end

  defp emit_def(%{name: name, type: ty, body: body} = d, book) do
    {:ok, ty_db} = Ast.to_db(ty)
    {:ok, body_db} = Ast.to_db(body)
    {erased, arity} = telescope(ty_db, 0, [])
    inner = peel_lams(body_db, arity)

    args =
      0..(arity - 1)//1
      |> Enum.reject(&(&1 in erased))
      |> Enum.map(&bound_name(inner, arity - 1 - &1, &1, book))

    expr = emit_db(inner, arity, book)
    kw = if Map.get(d, :export, true), do: "def", else: "defp"

    if args == [] do
      "#{kw} #{safe(name)} do\n  #{expr}\nend"
    else
      "#{kw} #{safe(name)}(#{Enum.join(args, ", ")}) do\n  #{expr}\nend"
    end
  end

  defp telescope({:pi, :erased, _, _, b}, i, er), do: telescope(b, i + 1, [i | er])
  defp telescope({:pi, _, _, _, b}, i, er), do: telescope(b, i + 1, er)
  defp telescope(_, i, er), do: {er, i}

  defp peel_lams({:lam, _, _, _, t}, n) when n > 0, do: peel_lams(t, n - 1)
  defp peel_lams(t, _), do: t

  # de Bruijn 0 is the nearest binder = last peeled λ = x#{depth-1}.
  defp emit_db({:var, i}, depth, _book), do: "x#{depth - 1 - i}"
  defp emit_db(:ze, _, _book), do: "0"
  defp emit_db(:one, _, _book), do: ":tt"
  defp emit_db({:su, u}, d, book), do: "{:suc, #{emit_db(u, d, book)}}"
  defp emit_db({:ann, e, _}, d, book), do: emit_db(e, d, book)
  defp emit_db(:rfl, _, _book), do: ":refl"
  defp emit_db({:rwt, _, _, t}, d, book), do: emit_db(t, d, book)

  defp emit_db({:hole, _}, _, _), do: raise("emit: hole")

  defp emit_db({:atom, n}, _, _book), do: elixir_atom(n)

  defp emit_db({:matom, e, _p, bs}, d, book) do
    clauses =
      Enum.map(bs, fn {name, b} ->
        "      #{elixir_atom(name)} -> #{emit_db(b, d, book)}"
      end)
      |> Enum.join("\n")

    """
    (case #{emit_db(e, d, book)} do
    #{clauses}
    end)
    """
    |> String.trim()
  end

  defp emit_db({:lam, :erased, _, _, t}, d, book), do: emit_db(t, d + 1, book)

  defp emit_db({:lam, _, _, _, t}, d, book) do
    "fn #{bound_name(t, 0, d, book)} -> #{emit_db(t, d + 1, book)} end"
  end

  defp emit_db({:mdata, e, _p, bs}, d, book) do
    clauses =
      Enum.map(bs, fn {name, ar, b} ->
        pat = emit_ctor_pat(name, ar, d, b, book)
        "      #{pat} -> #{emit_db(b, d + ar, book)}"
      end)
      |> Enum.join("\n")

    """
    (case #{emit_db(e, d, book)} do
    #{clauses}
    end)
    """
    |> String.trim()
  end

  defp emit_db({:mnat, e, _p, z, s}, d, book) do
    """
    case #{emit_db(e, d, book)} do
      0 -> #{emit_db(z, d, book)}
      {:suc, #{bound_name(s, 0, d, book)}} -> #{emit_db(s, d + 1, book)}
    end
    """
    |> String.trim()
  end

  defp emit_db({:memp, _, _}, _, _book), do: "raise \"Empty\""

  defp emit_db({:munit, e, _, u}, d, book) do
    "(#{emit_db(e, d, book)}; #{emit_db(u, d, book)})"
  end

  defp emit_db({:pair, a, b}, d, book), do: "{#{emit_db(a, d, book)}, #{emit_db(b, d, book)}}"
  # let (a, b) = e in t: a is de Bruijn 1 (x#{d}), b is de Bruijn 0 (x#{d + 1}).
  defp emit_db({:letp, e, t}, d, book) do
    a = bound_name(t, 1, d, book)
    b = bound_name(t, 0, d + 1, book)
    "({#{a}, #{b}} = #{emit_db(e, d, book)}; #{emit_db(t, d + 2, book)})"
  end

  defp emit_db({:unf, seed, f}, d, book) do
    "Stream.unfold(#{emit_db(seed, d, book)}, #{emit_db(f, d, book)})"
  end

  defp emit_db({:ucons, s}, d, book) do
    "(fn s -> {s |> Enum.take(1) |> hd(), Stream.drop(s, 1)} end).(#{emit_db(s, d, book)})"
  end

  defp emit_db({:addi, x, y}, d, book) do
    "Nx.add(#{emit_db(x, d, book)}, #{emit_db(y, d, book)})"
  end

  defp emit_db({:muli, x, y}, d, book) do
    "Nx.multiply(#{emit_db(x, d, book)}, #{emit_db(y, d, book)})"
  end

  defp emit_db({:addt, t, u}, d, book) do
    "Nx.add(#{emit_db(t, d, book)}, #{emit_db(u, d, book)})"
  end

  defp emit_db({:toi64, t}, d, book) do
    "Nx.tensor(muro_nat_to_int(#{emit_db(t, d, book)}), type: :s64)"
  end

  defp emit_db({:packi, x, y}, d, book) do
    "Nx.stack([#{emit_db(x, d, book)}, #{emit_db(y, d, book)}])"
  end

  defp emit_db({:app, _, _} = t, d, book) do
    {h, args} = spine(t, [])

    case h do
      {:def, n} ->
        if ctor_name?(book, n) do
          emit_ctor(n, args, d, book)
        else
          live = live_args(book, n, args, d)
          "#{safe(n)}(#{Enum.join(live, ", ")})"
        end

      _ ->
        Enum.reduce(args, emit_db(h, d, book), fn a, acc ->
          "#{acc}.(#{emit_db(a, d, book)})"
        end)
    end
  end

  defp emit_db({:def, n}, d, book) do
    if ctor_name?(book, n) do
      emit_ctor(n, [], d, book)
    else
      "#{safe(n)}()"
    end
  end

  defp emit_db(_, _, _book), do: "raise \"erased term\""

  defp emit_ctor(name, args, d, book) do
    xs = Enum.map(args, &emit_db(&1, d, book))

    case xs do
      [] -> ":#{safe(name)}"
      _ -> "{:#{safe(name)}, #{Enum.join(xs, ", ")}}"
    end
  end

  defp emit_ctor_pat(name, 0, _d, _body, _book), do: ":#{safe(name)}"

  defp emit_ctor_pat(name, ar, d, body, book) do
    vars = Enum.map(0..(ar - 1), fn i -> bound_name(body, ar - 1 - i, d + i, book) end)
    "{:#{safe(name)}, #{Enum.join(vars, ", ")}}"
  end

  # A binder the emitted term never mentions is `_`, so eval does not warn.
  defp bound_name(body, idx, slot, book) do
    if emitted_occurs?(idx, body, book), do: "x#{slot}", else: "_"
  end

  defp emitted_occurs?(i, {:var, j}, _), do: i == j
  defp emitted_occurs?(i, {:lam, _, _, _, t}, book), do: emitted_occurs?(i + 1, t, book)
  defp emitted_occurs?(i, {:su, t}, book), do: emitted_occurs?(i, t, book)
  defp emitted_occurs?(i, {:ann, e, _}, book), do: emitted_occurs?(i, e, book)
  defp emitted_occurs?(i, {:rwt, _, _, t}, book), do: emitted_occurs?(i, t, book)

  defp emitted_occurs?(i, {:pair, a, b}, book),
    do: emitted_occurs?(i, a, book) or emitted_occurs?(i, b, book)

  defp emitted_occurs?(i, {:letp, e, t}, book),
    do: emitted_occurs?(i, e, book) or emitted_occurs?(i + 2, t, book)

  defp emitted_occurs?(i, {:mnat, e, _, z, s}, book),
    do:
      emitted_occurs?(i, e, book) or emitted_occurs?(i, z, book) or
        emitted_occurs?(i + 1, s, book)

  defp emitted_occurs?(i, {:mdata, e, _, bs}, book) do
    emitted_occurs?(i, e, book) or
      Enum.any?(bs, fn {_, ar, b} -> emitted_occurs?(i + ar, b, book) end)
  end

  defp emitted_occurs?(i, {:matom, e, _, bs}, book) do
    emitted_occurs?(i, e, book) or
      Enum.any?(bs, fn {_, b} -> emitted_occurs?(i, b, book) end)
  end

  defp emitted_occurs?(i, {:munit, e, _, u}, book),
    do: emitted_occurs?(i, e, book) or emitted_occurs?(i, u, book)

  defp emitted_occurs?(i, {:unf, s, f}, book),
    do: emitted_occurs?(i, s, book) or emitted_occurs?(i, f, book)

  defp emitted_occurs?(i, {:ucons, s}, book), do: emitted_occurs?(i, s, book)

  defp emitted_occurs?(i, {:addi, a, b}, book),
    do: emitted_occurs?(i, a, book) or emitted_occurs?(i, b, book)

  defp emitted_occurs?(i, {:muli, a, b}, book),
    do: emitted_occurs?(i, a, book) or emitted_occurs?(i, b, book)

  defp emitted_occurs?(i, {:addt, a, b}, book),
    do: emitted_occurs?(i, a, book) or emitted_occurs?(i, b, book)

  defp emitted_occurs?(i, {:toi64, t}, book), do: emitted_occurs?(i, t, book)

  defp emitted_occurs?(i, {:packi, a, b}, book),
    do: emitted_occurs?(i, a, book) or emitted_occurs?(i, b, book)

  defp emitted_occurs?(i, {:app, _, _} = t, book) do
    {h, args} = spine(t, [])

    case h do
      {:def, n} ->
        if ctor_name?(book, n) do
          Enum.any?(args, &emitted_occurs?(i, &1, book))
        else
          args
          |> Enum.zip(arg_qtys(book, n, length(args)))
          |> Enum.reject(fn {_, q} -> q == :erased end)
          |> Enum.any?(fn {a, _} -> emitted_occurs?(i, a, book) end)
        end

      other ->
        emitted_occurs?(i, other, book) or Enum.any?(args, &emitted_occurs?(i, &1, book))
    end
  end

  defp emitted_occurs?(_, _, _), do: false

  defp arg_qtys(book, name, n) do
    case Enum.find(book, &(Map.get(&1, :kind, :def) != :data and &1.name == name)) do
      nil ->
        List.duplicate(:affine, n)

      dfn ->
        {:ok, ty} = Ast.to_db(dfn.type)
        qtys = qty_spine(ty)
        qtys ++ List.duplicate(:affine, max(n - length(qtys), 0))
    end
  end

  defp ctor_name?(book, name) do
    Enum.any?(book, fn
      %{kind: :data, ctors: cs} -> Enum.any?(cs, &(&1.name == name))
      _ -> false
    end)
  end

  defp live_args(book, name, args, d) do
    case Enum.find(book, &(Map.get(&1, :kind, :def) != :data and &1.name == name)) do
      nil ->
        Enum.map(args, &emit_db(&1, d, book))

      dfn ->
        {:ok, ty} = Ast.to_db(dfn.type)
        qtys = qty_spine(ty)

        args
        |> Enum.zip(qtys ++ List.duplicate(:affine, length(args)))
        |> Enum.reject(fn {_, q} -> q == :erased end)
        |> Enum.map(fn {a, _} -> emit_db(a, d, book) end)
    end
  end

  defp qty_spine({:pi, q, _, _, b}), do: [q | qty_spine(b)]
  defp qty_spine(_), do: []

  defp spine({:app, f, a}, acc), do: spine(f, [a | acc])
  defp spine(h, acc), do: {h, acc}

  defp elixir_atom(name) do
    if String.match?(name, ~r/^[A-Za-z_][A-Za-z0-9_@]*$/),
      do: ":#{name}",
      else: ":#{inspect(name)}"
  end

  defp safe(name) do
    name
    |> String.replace("-", "_")
    |> String.replace("'", "_")
  end

  defp term_has_toi64?({:toi64, _}), do: true

  defp term_has_toi64?(t) when is_tuple(t) do
    t |> Tuple.to_list() |> Enum.any?(&term_has_toi64?/1)
  end

  defp term_has_toi64?(t) when is_list(t), do: Enum.any?(t, &term_has_toi64?/1)
  defp term_has_toi64?(_), do: false

  defp indent(s, n) do
    pad = String.duplicate(" ", n)

    s
    |> String.split("\n")
    |> Enum.map(&(pad <> &1))
    |> Enum.join("\n")
  end
end
