------------------------------------------------------------------------
-- Inductive spec of MuroTT (core fragment).
--
-- fragment =
--   Type, Π/λ/app with Qty,
--   Nat / ze / su / mNat,
--   Empty / mEmp,
--   Unit / one / mUnit,
--   ≡ / refl / rewrite,
--   data: dty (spec only), constructor applications (checked against
--     a dty spine), match on a data type, indexed or not: the branch
--     of a constructor whose target indices clash with the scrutinee's
--     is skipped, every other branch binds all the constructor's
--     fields and is typed at the motive at the constructor's own
--     indices (no index is forced into the branch),
--   def lookup (allowedDef),
--   annotation,
--   A × B / (a, b) / let (a, b) = e in t (the tensor eliminator, in
--     both modes; fst / snd are surface sugar for it),
--   uses as in Check (spec forgets; run/evid count).
--
-- omitted = ν / Tensor / I64 / F32.
-- ⊢ does not track RecSt descent and does not use fuel. It does not
-- check the data declarations of σ (Check.checkData); Muro.Typing
-- states what preservation needs of them.
--
-- Conversion is the relation σ ⊢[ spec ] A ≈ B of Muro.Convert: the
-- equivalence generated by parallel reduction (δ, β, ι for Nat / Unit /
-- rewrite refl, ann; congruent under every constructor, binders
-- included). It is taken in spec mode, so every def unfolds, as in
-- Check.whnf: conversion is about types and does not see the wall. It
-- is used wherever Check normalises: ⇐-conv, ⇐-lam, ⇐-refl, and the
-- Π / ≡ views of application and rewrite (viewPi / viewId). See
-- Muro.Convert for what ≈ does not contain.
-- Check.agda remains the executable spec of the full language.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module Muro.Judgement where

open import Data.Bool.Base using (Bool; true; false; if_then_else_)
open import Data.Empty using (⊥)
open import Data.List.Base as List using (List; []; _∷_; _++_; length)
open import Data.Unit.Base using (tt)
open import Data.Fin.Base as Fin using ()
open import Data.Product.Base using (_×_; _,_; ∃)
open import Data.Nat.Base using (ℕ; zero; suc)
open import Data.Vec.Base as Vec using ([]; _∷_)
open import Relation.Binary.PropositionalEquality.Core using (_≡_; refl)

open import Muro.Base
open import Muro.Syntax
open import Muro.Subst using (inst; motSuc; closed; appsFrom; wk; motApp; motiveTail; renList)
open import Muro.Env
open import Muro.Convert using (_⊢[_]_≈_; ≈-trans; ≈-sym; ≈-ren)
open import Muro.Spine using (Spine)
open import Muro.Data

------------------------------------------------------------------------
-- Bidirectional ⊢. Uses sit in the conclusion (⊣). Two auxiliary
-- judgments for data: the arguments of a constructor application along
-- its telescope (T ▹ as ⇝ R: after the arguments as, the remaining
-- telescope is R; Check.inferCtorSpine), and the branches of a match,
-- one per constructor in declaration order.
------------------------------------------------------------------------

infix 3 _,_⊢[_]_⇒_⊣_ _,_⊢[_]_⇐_⊣_ _,_⊢_wf
infix 3 _,_⊢[_]_▹_⇝_⊣_ _,_⊢[_]_brs⟨_,_,_,_,_⟩_⊣_

data _,_⊢[_]_⇒_⊣_ (σ : Sig) {n} (Γ : Ctx n)
    : Mode → Tm n → Tm n → UseVec n → Set
data _,_⊢[_]_⇐_⊣_ (σ : Sig) {n} (Γ : Ctx n)
    : Mode → Tm n → Tm n → UseVec n → Set
data _,_⊢_wf (σ : Sig) {n} (Γ : Ctx n) : Tm n → Set
data _,_⊢[_]_▹_⇝_⊣_ (σ : Sig) {n} (Γ : Ctx n)
    : Mode → Tm n → List (Tm n) → Tm n → UseVec n → Set
data _,_⊢[_]_brs⟨_,_,_,_,_⟩_⊣_ (σ : Sig) {n} (Γ : Ctx n)
    : Mode → List (Tm n) → ℕ → List (Tm n) → List (Tm n) → Tm (suc n) → ℕ → List Ctor → UseVec n → Set
-- The motive of a match on data type di at parameters ps, whose index
-- telescope is ixs. Without indices it is a type over the scrutinee
-- (Check.checkMotive: checkTy); with indices it is checked, under the
-- first index, against the kind Π over the remaining indices and the
-- scrutinee, ending in Type (Check: check against motiveTail).
MotiveOk : ∀ (σ : Sig) {n} (Γ : Ctx n) → ℕ → List (Tm n) → List (Qty × Tm 0) → Tm (suc n) → Set

-- A well-formed type is the sort Type, a kind Π (x : A) → K, or a small
-- type (a term of type Type). Kinds are not small: Π (x : A) → Type is wf
-- and has no type. Otherwise Type would be a retract of a small type and
-- Girard's paradox would apply.
data _,_⊢_wf σ Γ where
  type-Type : σ , Γ ⊢ typ wf
  type-pi   : ∀ {q A B}
    → σ , Γ ⊢ A wf
    → σ , ext Γ q A ⊢ B wf
    → σ , Γ ⊢ pi q A B wf
  -- The sort is read through ≈ (Check.checkTy: infer, then conv with Type).
  type-el   : ∀ {A T u}
    → σ , Γ ⊢[ spec ] A ⇒ T ⊣ u
    → σ ⊢[ spec ] T ≈ typ
    → σ , Γ ⊢ A wf

data _,_⊢[_]_⇒_⊣_ σ Γ where

  ⇒-var-run : ∀ {x}
    → (qtyOf Γ x ≡ erased → ⊥)
    → σ , Γ ⊢[ run ] var x ⇒ typOf Γ x
        ⊣ oneHot x (if eqQty (qtyOf Γ x) reuse then Uω else U1)

  ⇒-var-evid : ∀ {x}
    → (qtyOf Γ x ≡ erased → ⊥)
    → σ , Γ ⊢[ evid ] var x ⇒ typOf Γ x
        ⊣ oneHot x (if eqQty (qtyOf Γ x) reuse then Uω else U1)

  ⇒-var-spec : ∀ {x}
    → σ , Γ ⊢[ spec ] var x ⇒ typOf Γ x ⊣ u0s

  ⇒-ze : ∀ {m} → σ , Γ ⊢[ m ] ze ⇒ nat ⊣ u0s
  ⇒-su : ∀ {m t u} → σ , Γ ⊢[ m ] t ⇐ nat ⊣ u → σ , Γ ⊢[ m ] su t ⇒ nat ⊣ u
  ⇒-one : ∀ {m} → σ , Γ ⊢[ m ] one ⇒ unit ⊣ u0s

  ⇒-nat   : σ , Γ ⊢[ spec ] nat   ⇒ typ ⊣ u0s
  ⇒-unit  : σ , Γ ⊢[ spec ] unit  ⇒ typ ⊣ u0s
  ⇒-empty : σ , Γ ⊢[ spec ] empty ⇒ typ ⊣ u0s

  -- The codomain is small. The domain may be a kind (Π (F : Nat → Type) → …).
  ⇒-pi : ∀ {q A B u}
    → σ , Γ ⊢ A wf
    → σ , ext Γ q A ⊢[ spec ] B ⇐ typ ⊣ u
    → σ , Γ ⊢[ spec ] pi q A B ⇒ typ ⊣ u0s

  ⇒-lam : ∀ {m q A t B u0 us}
    → σ , Γ ⊢ A wf
    → CopyOk σ q A
    → σ , ext Γ q A ⊢[ m ] t ⇒ B ⊣ (u0 ∷ us)
    → checkBound m q u0 ≡ ok tt
    → σ , Γ ⊢[ m ] lam q A t ⇒ pi q A B ⊣ us

  -- The function type is read through ≈ (Check: viewPi = whnf, then Π).
  -- Uses: Env.appUses (at a call site of an evidence definition in evid
  -- mode the argument's uses are discarded).
  ⇒-app-aff : ∀ {m F A B f a fu au uses}
    → σ , Γ ⊢[ m ] f ⇒ F ⊣ fu
    → σ ⊢[ spec ] F ≈ pi affine A B
    → σ , Γ ⊢[ m ] a ⇐ A ⊣ au
    → appUses σ m f fu au ≡ ok uses
    → σ , Γ ⊢[ m ] app f a ⇒ inst B a ⊣ uses

  ⇒-app-era : ∀ {m F A B f a fu au}
    → σ , Γ ⊢[ m ] f ⇒ F ⊣ fu
    → σ ⊢[ spec ] F ≈ pi erased A B
    → σ , Γ ⊢[ spec ] a ⇐ A ⊣ au
    → σ , Γ ⊢[ m ] app f a ⇒ inst B a ⊣ fu

  ⇒-app-reuse : ∀ {m F A B f a fu au uses}
    → σ , Γ ⊢[ m ] f ⇒ F ⊣ fu
    → σ ⊢[ spec ] F ≈ pi reuse A B
    → IsData σ A
    → σ , Γ ⊢[ m ] a ⇐ A ⊣ au
    → appUses σ m f fu au ≡ ok uses
    → σ , Γ ⊢[ m ] app f a ⇒ inst B a ⊣ uses

  -- A copyable argument that is not Data is a closure (or holds one):
  -- the function may apply it many times, so its uses are scaled to ω
  -- before they are combined. Check takes this rule when isData is
  -- false.
  ⇒-app-copy : ∀ {m F A B f a fu au uses}
    → σ , Γ ⊢[ m ] f ⇒ F ⊣ fu
    → σ ⊢[ spec ] F ≈ pi reuse A B
    → IsCopy σ A
    → σ , Γ ⊢[ m ] a ⇐ A ⊣ au
    → appUses σ m f fu (scaleω au) ≡ ok uses
    → σ , Γ ⊢[ m ] app f a ⇒ inst B a ⊣ uses

  -- The sort A may be a kind: {Nat ≡ Unit : Type} : Type. This is the one
  -- place a kind sits inside a small type. It is the shape of Coq's eq in
  -- impredicative Prop (a singleton family indexed by a large sort, with
  -- elimination allowed): refl carries no field, so rewrite cannot project
  -- a type back out, and no retract of Type arises.
  ⇒-idt : ∀ {A a b ua ub}
    → σ , Γ ⊢ A wf
    → σ , Γ ⊢[ spec ] a ⇐ A ⊣ ua
    → σ , Γ ⊢[ spec ] b ⇐ A ⊣ ub
    → σ , Γ ⊢[ spec ] idt A a b ⇒ typ ⊣ u0s

  -- The equation is evidence, or spec inside a spec term (rwtMode);
  -- its uses are discarded. The equation type is read through ≈
  -- (Check: viewId).
  ⇒-rwt : ∀ {m E A l r eq P t eu tu}
    → σ , Γ ⊢[ rwtMode m ] eq ⇒ E ⊣ eu
    → σ ⊢[ spec ] E ≈ idt A l r
    → σ , ext Γ affine A ⊢ P wf
    → σ , Γ ⊢[ m ] t ⇐ inst P r ⊣ tu
    → σ , Γ ⊢[ m ] rwt eq P t ⇒ inst P l ⊣ tu

  -- The predecessor is bound at predQty Γ e: reusable under a reusable
  -- variable, affine otherwise.
  ⇒-mNat : ∀ {m e P z s eu zu u0 sus uses}
    → σ , Γ ⊢[ m ] e ⇐ nat ⊣ eu
    → σ , ext Γ affine nat ⊢ P wf
    → σ , Γ ⊢[ m ] z ⇐ inst P ze ⊣ zu
    → σ , ext Γ (predQty Γ e) nat ⊢[ m ] s ⇐ motSuc P ⊣ (u0 ∷ sus)
    → checkBound m (predQty Γ e) u0 ≡ ok tt
    → combine m eu (combineAlt m zu sus) ≡ ok uses
    → σ , Γ ⊢[ m ] mNat e P z s ⇒ inst P e ⊣ uses

  ⇒-mEmp : ∀ {m e P eu}
    → σ , Γ ⊢[ m ] e ⇐ empty ⊣ eu
    → σ , ext Γ affine empty ⊢ P wf
    → σ , Γ ⊢[ m ] mEmp e P ⇒ inst P e ⊣ eu

  ⇒-mUnit : ∀ {m e P tu eu uu uses}
    → σ , Γ ⊢[ m ] e ⇐ unit ⊣ eu
    → σ , ext Γ affine unit ⊢ P wf
    → σ , Γ ⊢[ m ] tu ⇐ inst P one ⊣ uu
    → combine m eu uu ≡ ok uses
    → σ , Γ ⊢[ m ] mUnit e P tu ⇒ inst P e ⊣ uses

  -- A data former is an erased term: spec only (Check: no promotion).
  ⇒-dty : ∀ {i d}
    → lookupData σ i ≡ ok d
    → σ , Γ ⊢[ spec ] dty i ⇒ dtyType (DataDecl.pqtys d) (DataDecl.idxs d) ⊣ u0s

  -- match on a data type. The scrutinee's type is read through ≈ as
  -- dty di applied to its parameters and indices (Check: viewData); the
  -- motive is over the indices and the scrutinee (MotiveOk); one branch
  -- per constructor in declaration order, typed by BrTy or skipped when
  -- its indices clash. The type is the motive at the scrutinee's
  -- indices and the scrutinee. Check returns the motive as a λ applied
  -- to indices and scrutinee, which is β-convertible to motApp.
  ⇒-mData : ∀ {m e E di ps is d P bs eu bu uses}
    → σ , Γ ⊢[ m ] e ⇒ E ⊣ eu
    → σ ⊢[ spec ] E ≈ appsFrom (dty di) (ps ++ is)
    → lookupData σ di ≡ ok d
    → length ps ≡ nparams d
    → length is ≡ nidxs d
    → MotiveOk σ Γ di ps (DataDecl.idxs d) P
    → σ , Γ ⊢[ m ] bs brs⟨ di , ps , is , P , 0 ⟩ DataDecl.ctors d ⊣ bu
    → combine m eu bu ≡ ok uses
    → σ , Γ ⊢[ m ] mData e P bs ⇒ motApp P is e ⊣ uses

  ⇒-def : ∀ {m i d}
    → lookupDef σ i ≡ ok d
    → allowedDef (Def.dmode d) m ≡ true
    → σ , Γ ⊢[ m ] def i ⇒ closed (Def.dtype d) ⊣ u0s

  ⇒-ann : ∀ {m e A u}
    → σ , Γ ⊢ A wf
    → σ , Γ ⊢[ m ] e ⇐ A ⊣ u
    → σ , Γ ⊢[ m ] ann e A ⇒ A ⊣ u

  -- A × B is small, an erased term: spec only (Check: no promotion).
  ⇒-prod : ∀ {A B ua ub}
    → σ , Γ ⊢[ spec ] A ⇐ typ ⊣ ua
    → σ , Γ ⊢[ spec ] B ⇐ typ ⊣ ub
    → σ , Γ ⊢[ spec ] prod A B ⇒ typ ⊣ u0s

  ⇒-pair : ∀ {m a b A B au bu uses}
    → σ , Γ ⊢[ m ] a ⇒ A ⊣ au
    → σ , Γ ⊢[ m ] b ⇒ B ⊣ bu
    → combine m au bu ≡ ok uses
    → σ , Γ ⊢[ m ] pair a b ⇒ prod A B ⊣ uses

  -- let (a, b) = e in t in inference mode. The body is inferred under
  -- the two affine binders and its type must be convertible to a type
  -- that does not mention them, wk (wk C) (Check: strengthen₂ on the
  -- inferred type). Its uses are treated as in ⇐-letp.
  ⇒-letp : ∀ {m e E A B t T C eu ua ub tus uses}
    → σ , Γ ⊢[ m ] e ⇒ E ⊣ eu
    → σ ⊢[ spec ] E ≈ prod A B
    → σ , ext (ext Γ affine A) affine (wk B) ⊢[ m ] t ⇒ T ⊣ (ub ∷ ua ∷ tus)
    → σ ⊢[ spec ] T ≈ wk (wk C)
    → checkBound m affine ub ≡ ok tt
    → checkBound m affine ua ≡ ok tt
    → combine m eu tus ≡ ok uses
    → σ , Γ ⊢[ m ] letp e t ⇒ C ⊣ uses

data _,_⊢[_]_⇐_⊣_ σ Γ where
  ⇐-conv : ∀ {m e A B u}
    → σ , Γ ⊢[ m ] e ⇒ B ⊣ u
    → σ ⊢[ spec ] B ≈ A
    → σ , Γ ⊢[ m ] e ⇐ A ⊣ u

  -- The expected type is read through ≈ (Check: viewPi), so ⇐ is
  -- closed under conversion of the type (⇐-≈ below).
  ⇐-lam : ∀ {m q A A′ t B T u0 us}
    → σ , Γ ⊢ A wf
    → σ ⊢[ spec ] T ≈ pi q A′ B
    → σ ⊢[ spec ] A ≈ A′
    → CopyOk σ q A′
    → σ , ext Γ q A′ ⊢[ m ] t ⇐ B ⊣ (u0 ∷ us)
    → checkBound m q u0 ≡ ok tt
    → σ , Γ ⊢[ m ] lam q A t ⇐ T ⊣ us

  ⇐-refl : ∀ {m T A a b}
    → σ ⊢[ spec ] T ≈ idt A a b
    → σ ⊢[ spec ] a ≈ b
    → σ , Γ ⊢[ m ] rfl ⇐ T ⊣ u0s

  -- The expected type is read through ≈ (Check: viewProd).
  ⇐-pair : ∀ {m T A B a b au bu uses}
    → σ ⊢[ spec ] T ≈ prod A B
    → σ , Γ ⊢[ m ] a ⇐ A ⊣ au
    → σ , Γ ⊢[ m ] b ⇐ B ⊣ bu
    → combine m au bu ≡ ok uses
    → σ , Γ ⊢[ m ] pair a b ⇐ T ⊣ uses

  -- let (a, b) = e in t. The scrutinee's type is read through ≈ as a
  -- product (Check: viewProd); the body is checked under two affine
  -- binders (a at var 1, b at var 0) against the expected type weakened
  -- twice; each binder's uses are bounded and the rest combined with
  -- the scrutinee's. A let whose body has a type not mentioning the
  -- binders is also inferred (⇒-letp).
  ⇐-letp : ∀ {m e E A B t C eu ua ub tus uses}
    → σ , Γ ⊢[ m ] e ⇒ E ⊣ eu
    → σ ⊢[ spec ] E ≈ prod A B
    → σ , ext (ext Γ affine A) affine (wk B) ⊢[ m ] t ⇐ wk (wk C) ⊣ (ub ∷ ua ∷ tus)
    → checkBound m affine ub ≡ ok tt
    → checkBound m affine ua ≡ ok tt
    → combine m eu tus ≡ ok uses
    → σ , Γ ⊢[ m ] letp e t ⇐ C ⊣ uses

  -- A constructor application ctor di ci a₁ … aₙ is checked against a
  -- data type (Check: viewData on the expected type, then
  -- checkCtorApp). The parameters come from the expected type, not from
  -- the term; the constructor's type with the parameters instantiated
  -- is walked along the arguments, and the residual telescope must be
  -- the expected type.
  ⇐-ctor : ∀ {m e A di ci as ps idxs d c T R u}
    → Spine (ctor di ci) as e
    → σ ⊢[ spec ] A ≈ appsFrom (dty di) (ps ++ idxs)
    → lookupData σ di ≡ ok d
    → length ps ≡ nparams d
    → length idxs ≡ nidxs d
    → lookupCtor d ci ≡ ok c
    → InstParams σ (closed (Ctor.ctype c)) ps T
    → σ , Γ ⊢[ m ] T ▹ as ⇝ R ⊣ u
    → σ ⊢[ spec ] R ≈ appsFrom (dty di) (ps ++ idxs)
    → σ , Γ ⊢[ m ] e ⇐ A ⊣ u

-- Arguments along a telescope, from the head of the spine outwards
-- (Check.inferCtorSpine, as the spine is built): after as the remaining
-- telescope R is a Π, the next argument is checked against its domain,
-- an erased field in spec contributing no uses.
data _,_⊢[_]_▹_⇝_⊣_ σ Γ where
  args-[] : ∀ {m T}
    → σ , Γ ⊢[ m ] T ▹ [] ⇝ T ⊣ u0s

  args-snoc : ∀ {m T q A B a as R asu au uses}
    → σ , Γ ⊢[ m ] T ▹ as ⇝ R ⊣ asu
    → σ ⊢[ spec ] R ≈ pi q A B
    → ReuseOk σ q A
    → σ , Γ ⊢[ fieldMode q m ] a ⇐ A ⊣ au
    → combineArg q m au asu ≡ ok uses
    → σ , Γ ⊢[ m ] T ▹ (as ++ (a ∷ [])) ⇝ inst B a ⊣ uses

  -- A + field whose type is copyable but not Data: the argument's uses
  -- are scaled to ω, as in ⇒-app-copy.
  args-snoc-copy : ∀ {m T A B a as R asu au uses}
    → σ , Γ ⊢[ m ] T ▹ as ⇝ R ⊣ asu
    → σ ⊢[ spec ] R ≈ pi reuse A B
    → IsCopy σ A
    → σ , Γ ⊢[ m ] a ⇐ A ⊣ au
    → combineArg reuse m (scaleω au) asu ≡ ok uses
    → σ , Γ ⊢[ m ] T ▹ (as ++ (a ∷ [])) ⇝ inst B a ⊣ uses

-- Branches, one per constructor. A constructor whose telescope (at the
-- parameters) targets indices clashing with the scrutinee's is skipped:
-- its branch term is consumed, not typed (Check.checkBranches).
data _,_⊢[_]_brs⟨_,_,_,_,_⟩_⊣_ σ Γ where
  brs-[] : ∀ {m di ps is P ci}
    → σ , Γ ⊢[ m ] [] brs⟨ di , ps , is , P , ci ⟩ [] ⊣ u0s

  brs-∷ : ∀ {m di ps is P ci c cs b bs T X u v}
    → InstParams σ (closed (Ctor.ctype c)) ps T
    → BrTy σ di ci (length ps) T P [] X
    → σ , Γ ⊢[ m ] b ⇐ X ⊣ u
    → σ , Γ ⊢[ m ] bs brs⟨ di , ps , is , P , suc ci ⟩ cs ⊣ v
    → σ , Γ ⊢[ m ] (b ∷ bs) brs⟨ di , ps , is , P , ci ⟩ (c ∷ cs) ⊣ combineAlt m u v

  brs-skip : ∀ {m di ps is P ci c cs b bs T v}
    → InstParams σ (closed (Ctor.ctype c)) ps T
    → Clash σ (length ps) is T
    → σ , Γ ⊢[ m ] bs brs⟨ di , ps , is , P , suc ci ⟩ cs ⊣ v
    → σ , Γ ⊢[ m ] (b ∷ bs) brs⟨ di , ps , is , P , ci ⟩ (c ∷ cs) ⊣ v

MotiveOk σ Γ di ps [] P =
  σ , ext Γ affine (appsFrom (dty di) ps) ⊢ P wf
MotiveOk σ Γ di ps ((q , T) ∷ ixs) P =
  ∃ λ u → σ , ext Γ q (closed T) ⊢[ spec ] P ⇐ motiveTail di (renList Fin.suc ps ++ (var Fin.zero ∷ [])) ixs ⊣ u

------------------------------------------------------------------------
-- Empty signature / empty context (for Wall and Consistency).
------------------------------------------------------------------------

-- ⇐ is closed under conversion of the expected type: every ⇐ rule
-- reads its type through ≈.
⇐-≈ : ∀ {σ n} {Γ : Ctx n} {m e A A′ u}
  → σ , Γ ⊢[ m ] e ⇐ A ⊣ u → σ ⊢[ spec ] A ≈ A′ → σ , Γ ⊢[ m ] e ⇐ A′ ⊣ u
⇐-≈ (⇐-conv D c) c′ = ⇐-conv D (≈-trans c c′)
⇐-≈ (⇐-lam W c cA rok D b) c′ = ⇐-lam W (≈-trans (≈-sym c′) c) cA rok D b
⇐-≈ (⇐-refl c cab) c′ = ⇐-refl (≈-trans (≈-sym c′) c) cab
⇐-≈ (⇐-ctor sp c lk lps lidx lkc ip Ar cR) c′ = ⇐-ctor sp (≈-trans (≈-sym c′) c) lk lps lidx lkc ip Ar cR
⇐-≈ (⇐-pair c Da Db cu) c′ = ⇐-pair (≈-trans (≈-sym c′) c) Da Db cu
⇐-≈ (⇐-letp De c Dt bb ba cu) c′ =
  ⇐-letp De c (⇐-≈ Dt (≈-ren Fin.suc (≈-ren Fin.suc c′))) bb ba cu

σ-empty : Sig
σ-empty = mkSig [] []

ε : Ctx 0
ε = Vec.[]
